name: docs

on:
  push:
    branches:
      - main  
    tags:
      # only run on for releases, beta and docs releases
      - v*
      
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: python:3.9
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Requirements
        run: pip install -r ./docs/requirements.txt
      - name: Build with MkDocs (validation)
        run: |
          mkdocs build --verbose --clean
          rm -r site/
      - name: Configure Git
        if: startsWith(github.ref, 'refs/tags/')
        id: git
        run: |
          git config --global user.name pipeline-container-desktop.io
          git config --global user.email pipeline@container-desktop.io
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Build & Deploy with Mike (versioned)
        if: startsWith(github.ref, 'refs/tags/')
        #mike deploy --branch gh-pages --push test
        run: |
          mike deploy --update-aliases --push --rebase ${{ steps.git.outputs.tag }} latest